@port= 8080



# MATERIAS
@id=1

http://localhost:{{port}}/api/materias/

###

POST http://localhost:{{port}}/api/materias/ HTTP/1.1
content-type: application/json

{
    "nome": "exemplo"
}

###

PUT http://localhost:{{port}}/api/materias/{{id}} HTTP/1.1
content-type: application/json

{
    "nome": "exemplo editado 2"
}

###

DELETE http://localhost:{{port}}/api/materias/{{id}} HTTP/1.1
content-type: application/json




# PROFESSORES
@id=1

###

http://localhost:{{port}}/api/professores/

###

POST http://localhost:{{port}}/api/professores/ HTTP/1.1
content-type: application/json

{
    "nome": "Professor 1",
    "whatsapp": "123456789",
    "short_bio": "um professor bunitu y inteligente",
    "materias_id": [1, 2, 3]
}

###

PUT http://localhost:{{port}}/api/professores/{{id}} HTTP/1.1
content-type: application/json

{
    "nome": "Professor (editado)",
    "whatsapp": "123456789",
    "short_bio": "um professor bunitu y inteligente",
    "materias_id": [1, 2, 3]
}

###

DELETE http://localhost:{{port}}/api/professores/{{id}} HTTP/1.1
content-type: application/json



# AULAS
@id=1

###

http://localhost:{{port}}/api/aulas/

###

POST http://localhost:{{port}}/api/aulas/ HTTP/1.1
content-type: application/json

{
    "materia_id": 1,
    "professor_id": 1,
    "preco": "50",
    "inicio": "12:00",
    "fim": "15:00",
    "dia": 1
}

###

PUT http://localhost:{{port}}/api/aulas/{{id}} HTTP/1.1
content-type: application/json

{
    "nome": "Professor (editado)",
    "whatsapp": "123456789",
    "short_bio": "um professor bunitu y inteligente",
    "materias_id": [1, 2, 3]
}

###

DELETE http://localhost:{{port}}/api/aulas/{{id}} HTTP/1.1
content-type: application/json
